### ISSUE TITLE
Docs or code for patterns are wrong

### ISSUE THREAD

**Issue by eudaimos** [taoyuan/needs#1]
Currently the docs show the use of `RegExp`s as patterns for `includes` and `excludes` but looking at the code it's expecting `String`s because it's calling `pattern.indexOf(…)` here: [lib/needs.js:20](../blob/master/lib/needs.js#L20)

When I tried to pass a `RegExp` to `excludes` like `excludes: /index\.js/` I received:

``` shell
TypeError: undefined is not a function
    at .../node_modules/needs/lib/needs.js:20:33
    ....
```

Changing it to `excludes: 'index\.js'` it works

**Comment by taoyuan** [comment]
Thanks for reporting. I fixed it just now. Would you like to check it ?
